name: Push Folder to IPFS
on:
  workflow_dispatch
jobs:
  PushToIPFS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check dir
        run: |
          ls
      - name: Upload to IPFS
        uses: aquiladev/ipfs-action@v0.3.1-alpha.2
        with:
          path: ./data
